**Numpy 是Python数值计算重要的基础包，大多数提供科学计算的包都是用Numpy的数组作为构建基础**
### Numpy的部分功能如下
* ndarray 一个具有矢量算术运算和复杂广播的快速且节省空间的多维数组
* 用于对整组数据进行快速运算的标准数学函数 (无需编写循环)
* 用于读写磁盘数据的工具以及用于操作内存映射文件的工具
* 线性代数、随机数生成、傅里叶变换功能
* 用于集成由C、C++、Fortran等语言编写的代码的AC API
### Numpy可以高效处理大数组数据的原因:
* Numpy是在一个连续的内存块中存储数据，独立于其他Python内置对象
* Numpy的C语言编写的算法库可以操作内存，而不必进行类型检查或其他前期工作，比起python内置序列，Numpy数组使用的内存更少
* Numpy可以在整个数组上执行复杂的计算，而不需要python的for循环

# Numpy的ndarray：一种多维数组对象

In [10]:
# numpy最重要的一个特点就是它的N维数组对象(ndarray),该对象是一个快速而灵活的大数据集容器
import numpy as np
data = np.random.randn(2, 3)
print(data, "\n")
print(data * 10, "\n")
print(data + data, "\n")
# ndarray是一个通用的同构数据多维容器，所有元素必须是相同类型的,每个数组都有一个shape 和 一个dtype
print(data.shape)
print(data.dtype)

[[-1.03433033  0.09335385 -0.10496624]
 [-1.76665867 -1.21353481 -0.56444107]] 

[[-10.34330326   0.93353852  -1.04966236]
 [-17.66658666 -12.13534814  -5.64441068]] 

[[-2.06866065  0.1867077  -0.20993247]
 [-3.53331733 -2.42706963 -1.12888214]] 

(2, 3)
float64


#### 创建 ndarray

In [18]:
# 创建数组最简单的办法就是使用array函数
data = [1, 1.45, 4, 7]
data = np.array(data)
print(data, "\n")
# data2 是列表的列表，numpy数组arr2的两个维度的shape是从data2引入的
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2, "维度: ",arr2.ndim, "形状: ", arr2.shape)

# 使用zeros和ones函数可以创建指定长度或形状的全是0或全是1的数组
print(np.zeros(10), "\n")
print(np.zeros((3, 4)))


[1.   1.45 4.   7.  ] 

[[1 2 3 4]
 [5 6 7 8]] 维度:  2 形状:  (2, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ndarray的数据类型

In [19]:
# dtype 是一个特殊的对象，它含有 ndarray将一块内存解释为特定数据类型所需的信息
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print("arr1数据类型:{}, arr2数据类型:{}".format(arr1.dtype, arr2.dtype))


arr1数据类型:float64, arr2数据类型:int32
